/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Profile, Sect, District, EducationType } from "./types";

export const SAMPLE_PROFILES: Profile[] = [
  {
    id: "prof_1",
    fullName: "Fathima Riza",
    gender: "Female",
    age: 24,
    height: 162,
    weight: 54,
    district: District.Kozhikode,
    sect: Sect.Sunni_EK,
    education: EducationType.Doctor,
    educationDetails: "MBBS, MD (Pediatrics)",
    occupation: "Pediatrician",
    company: "Aster MIMS Hospital, Kozhikode",
    incomeRange: "₹12L - ₹15L per annum",
    aboutMe: "Assalamu Alaikum. I am a compassionate, family-oriented individual who balances both professional commitments and religious values. I am looking for a partner who is well-educated, respectful, and values family traditions and religious principles.",
    religiousPractice: "Practicing",
    hobbies: ["Reading Islamic literature", "Baking", "Gardening", "Caligraphy"],
    photos: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-05-15",
    family: {
      fatherName: "K.P. Abdul Majeed",
      fatherOccupation: "Retired Government High School Principal",
      motherName: "Suhara Majeed",
      motherOccupation: "Homemaker",
      familyStatus: "Upper Middle Class",
      familyValues: "Traditional",
      siblingsDetails: "One elder brother (Software Engineer in Dubai, married), one younger sister (B.Tech student at NIT Calicut)",
      nativePlace: "Kondotty, Malappuram",
    },
    phone: "+91 9447234567"
  },
  {
    id: "prof_2",
    fullName: "Mohammed Anas",
    gender: "Male",
    age: 27,
    height: 178,
    weight: 72,
    district: District.Malappuram,
    sect: Sect.Sunni_EK,
    education: EducationType.Engineer,
    educationDetails: "B.Tech in Computer Science, NIT Calicut",
    occupation: "Senior Software Engineer",
    company: "Oracle India, InfoPark Kochi",
    incomeRange: "₹18L - ₹22L per annum",
    aboutMe: "Hello. I am a simple, down-to-earth person who believes in leading a balanced life. Professionally ambitious but deeply rooted in our cultural and family values. I pray five times a day and always try to improve my character. Looking for an educated partner from Kerala who shares similar ideals.",
    religiousPractice: "Practicing",
    hobbies: ["Football (Sevens)", "Photography", "Traveling", "Volunteering"],
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-06-10",
    family: {
      fatherName: "Chakkalakkal Usman Haji",
      fatherOccupation: "Business Owner (Malabar Spices & Textiles)",
      motherName: "Amina Usman",
      motherOccupation: "Homemaker",
      familyStatus: "Upper Middle Class",
      familyValues: "Moderate",
      siblingsDetails: "Two elder sisters (Both married and settled in Malappuram and Kozhikode)",
      nativePlace: "Perinthalmanna, Malappuram",
    },
    phone: "+91 9846123456"
  },
  {
    id: "prof_3",
    fullName: "Aisha Nisrin",
    gender: "Female",
    age: 23,
    height: 158,
    weight: 50,
    district: District.Ernakulam,
    sect: Sect.Mujahid_KNM,
    education: EducationType.CharteredAccountant,
    educationDetails: "Chartered Accountant (ICAI)",
    occupation: "Auditor / Financial consultant",
    company: "Ernst & Young (EY), Kochi",
    incomeRange: "₹10L - ₹12L per annum",
    aboutMe: "Assalamu Alaikum, I am Aisha. I value honesty, intellectual growth, and religious clarity. I am looking for a partner who is progressive yet strongly adheres to Islamic values in daily life. I prefer someone with a professional background who appreciates working women.",
    religiousPractice: "Very practicing",
    hobbies: ["Public speaking", "Numismatics", "Cooking Malabar dishes", "Coding"],
    photos: [
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-04-22",
    family: {
      fatherName: "T.M. Faisal Ahmed",
      fatherOccupation: "General Manager in Muscat, Oman",
      motherName: "Jameela Faisal",
      motherOccupation: "Teacher (UP School)",
      familyStatus: "Upper Middle Class",
      familyValues: "Moderate",
      siblingsDetails: "One younger brother doing BBA at Christ University, Bangalore",
      nativePlace: "Aluva, Ernakulam",
    },
    phone: "+91 9995543210"
  },
  {
    id: "prof_4",
    fullName: "Nihal Ahmed",
    gender: "Male",
    age: 29,
    height: 181,
    weight: 78,
    district: District.NRI_GCC,
    sect: Sect.General,
    education: EducationType.PostGraduate,
    educationDetails: "MBA in Finance & Marketing, CUSAT",
    occupation: "Investment Analyst",
    company: "Emirates NBD, Dubai, UAE",
    incomeRange: "AED 120,000 - 150,000 per annum",
    aboutMe: "I am a positive, highly driven individual residing in Dubai. Originally from Kozhikode, Kerala. I love traveling, exploring different cuisines, and keeping a healthy lifestyle. Looking for a partner who is open-minded, educated, enjoys life, and is willing to relocate to Dubai.",
    religiousPractice: "Moderate",
    hobbies: ["Traveling", "Gym & Fitness", "Reading Tech Blogs", "Trekking"],
    photos: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-05-30",
    family: {
      fatherName: "Advocate P.V. Ibrahim",
      fatherOccupation: "Practicing Lawyer (High Court of Kerala)",
      motherName: "Dr. Naseema Ibrahim",
      motherOccupation: "Gynecologist (Government Service)",
      familyStatus: "Affluent",
      familyValues: "Moderate",
      siblingsDetails: "One elder brother (Senior Consultant Pediatrician in Malappuram), married.",
      nativePlace: "Vatakara, Kozhikode",
    },
    phone: "+971 50 1234567"
  },
  {
    id: "prof_5",
    fullName: "Thasni Banu",
    gender: "Female",
    age: 26,
    height: 160,
    weight: 52,
    district: District.Kannur,
    sect: Sect.General,
    education: EducationType.Graduate,
    educationDetails: "B.Sc Nursing, Government Nursing College, Kozhikode",
    occupation: "Registered Nurse",
    company: "Aster MIMS Hospital, Kannur",
    incomeRange: "₹4L - ₹6L per annum",
    aboutMe: "Hi. I am an active, caring, and cheerful person. I cherish simplicity and mutual understanding. I am passionate about my profession in healthcare. I am searching for a life partner who is caring, has clean habits, holds moral values, and will support my career goals.",
    religiousPractice: "Practicing",
    hobbies: ["Listening to Sufi songs", "Handicrafts", "Reading fiction", "Badminton"],
    photos: [
      "https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-03-12",
    family: {
      fatherName: "K. Hamza (Late)",
      fatherOccupation: "Was Merchant",
      motherName: "Sakeena Hamza",
      motherOccupation: "Homemaker",
      familyStatus: "Middle Class",
      familyValues: "Traditional",
      siblingsDetails: "Two elder brothers (One doing business in Kannur, second is working as Accountant in Qatar)",
      nativePlace: "Thalassery, Kannur",
    },
    phone: "+91 9895012345"
  },
  {
    id: "prof_6",
    fullName: "Ameer Suhail",
    gender: "Male",
    age: 30,
    height: 175,
    weight: 70,
    district: District.Kannur,
    sect: Sect.Sunni_AP,
    education: EducationType.Doctor,
    educationDetails: "MD in General Medicine, Government Medical College Trivandrum",
    occupation: "Senior Resident Physician",
    company: "Government Medical College, Kannur",
    incomeRange: "₹14L - ₹18L per annum",
    aboutMe: "I am Ameer, working as a doctor in Kannur. I value moral ethics, religious compliance, and intellectual debates. I look forward to meeting an understanding and humble partner who balances religious virtues and professional excellence.",
    religiousPractice: "Practicing",
    hobbies: ["Medical journaling", "Chess", "Cycling", "Charity work"],
    photos: [
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-02-18",
    family: {
      fatherName: "Dr. K.P. Mahmood",
      fatherOccupation: "Retired Chief Medical Officer, Kannur",
      motherName: "Faisalath Mahmood",
      motherOccupation: "Retired High School Teacher",
      familyStatus: "Affluent",
      familyValues: "Traditional",
      siblingsDetails: "One younger brother doing MD in Radiology, Bangalore. One sister married and settled in Calicut.",
      nativePlace: "Thana, Kannur",
    },
    phone: "+91 9744112233"
  },
  {
    id: "prof_7",
    fullName: "Suhara Shabeer",
    gender: "Female",
    age: 25,
    height: 165,
    weight: 56,
    district: District.Wayanad,
    sect: Sect.General,
    education: EducationType.PostGraduate,
    educationDetails: "M.Sc in Biotechnology, Calicut University",
    occupation: "Research Associate",
    company: "Biotech Research Lab, Kochi",
    incomeRange: "₹6L - ₹8L per annum",
    aboutMe: "I am a progressive thinker who strongly values our heritage. I enjoy exploring nature, doing science, and learning new skills. Looking for a partner with similar research/tech inclination, who is well-mannered and respects individual space and choices.",
    religiousPractice: "Moderate",
    hobbies: ["Nature trails", "Scientific writing", "Photography", "Playing piano"],
    photos: [
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-06-01",
    family: {
      fatherName: "Shabeer Ahmed",
      fatherOccupation: "Spice Plantation Owner in Wayanad",
      motherName: "Rehana Shabeer",
      motherOccupation: "School Principal",
      familyStatus: "Upper Middle Class",
      familyValues: "Moderate",
      siblingsDetails: "One elder sister (Settled in Bangalore with family), one younger brother (Doing B.Arch in CET Trivandrum)",
      nativePlace: "Kalpetta, Wayanad",
    },
    phone: "+91 9188098765"
  },
  {
    id: "prof_8",
    fullName: "Shamil K.P.",
    gender: "Male",
    age: 26,
    height: 172,
    weight: 68,
    district: District.Kozhikode,
    sect: Sect.Jamaat,
    education: EducationType.PostGraduate,
    educationDetails: "MCA, CUSAT Kochi",
    occupation: "UI/UX Designer & Frontend Dev",
    company: "Tech Start-up, Kozhikode Cyberpark",
    incomeRange: "₹8L - ₹10L per annum",
    aboutMe: "Hi there! I am a creative soul who loves blending design and technology. I am looking for a companion who is creative, simple-hearted, and possesses a cheerful outlook on life. Values moral standards and enjoys simple family gatherings.",
    religiousPractice: "Practicing",
    hobbies: ["Sketching", "Designing", "Listening to Malabar Mappilapattukal", "Watching football"],
    photos: [
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1489980508314-941910ded1f4?auto=format&fit=crop&q=80&w=600",
    ],
    isVerified: true,
    verifiedDate: "2026-05-19",
    family: {
      fatherName: "K.P. Shareef",
      fatherOccupation: "Merchant in Kozhikode Valiyangadi",
      motherName: "Nafisah Shareef",
      motherOccupation: "Homemaker",
      familyStatus: "Middle Class",
      familyValues: "Moderate",
      siblingsDetails: "One elder sister (Married, settled in Kochi), one younger sister (B.Com student)",
      nativePlace: "Pantheerankavu, Kozhikode",
    },
    phone: "+91 9567888999"
  }
];
